# Commit Message Linter Configuration
# Documentation: https://github.com/breml/githooks

rules:
  # Prevent WIP (work-in-progress) commits from being pushed
  - name: prevent-wip
    type: deny                                              # fail if pattern matches
    scope: title                                            # check only the first line
    pattern: '(?i)(?:^|[\s\(\)])(wip)(?:[\s\(\):]|$)'       # case-insensitive WIP detection
    message: "WIP commits are not allowed to be pushed"

  # Require Conventional Commits format
  - name: conventional-commits
    type: require
    scope: title
    pattern: '^(feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert)(\([a-z0-9-]+\))?!?: .+'
    message: "Commit title must follow Conventional Commits format (e.g., 'feat: add feature')"

  # Prevent fixup commits from being pushed
  - name: no-fixup
    type: deny
    scope: title
    pattern: '^fixup!'
    message: "Fixup commits should be squashed before pushing"

  # Prevent emoji in commit messages by excluding Unicode symbol characters
  - name: no-emoji
    type: deny
    scope: message
    pattern: '\p{So}'
    message: "Commit messages must not contain emoji characters or symbols"

  # Enforce title length limit (72 characters)
  - name: title-max-length
    type: deny
    scope: title
    pattern: '^.{73,}'
    message: "Commit title must not exceed 72 characters"

  # Enforce no Generated by line in commit messages
  - name: no-generated-by
    type: deny
    scope: message
    pattern: '^Generated by'
    message: "Commit messages must not contain 'Generated by' lines"

# Additional example rules (uncomment to enable):

#  # Prevent emoji in commit messages
#  - name: no-emoji
#    type: deny
#    scope: message
#    pattern: [\x{1F300}-\x{1F64F}\x{1F680}-\x{1F6FF}]
#    message: "Commit messages must not contain emoji characters"


# # Require DCO (Developer Certificate of Origin) sign-off
# - name: require-signoff
#   type: require
#   scope: footer
#   pattern: '^Signed-off-by: .+ <.+@.+>$'
#   message: "Commits must include 'Signed-off-by' trailer (use git commit -s)"

# # Require issue reference
# - name: require-issue-ref
#   type: require
#   scope: message
#   pattern: '(?i)(close[sd]?|fix(e[sd])?|resolve[sd]?|ref(erence)?):?\s*#\d+'
#   message: "Commit must reference an issue (e.g., 'Fixes #123')"

# Global settings (optional)
settings:
  # Stop on first rule violation (default: false - report all violations)
  fail_fast: false

  # Skip merge commits (default: true)
  skip_merge_commits: true

  main_ref: master

  # Skip commits by specific authors (regex patterns)
  # skip_authors:
  #   - 'renovate\[bot\]'
  #   - 'dependabot\[bot\]'
  #   - '.*@users\.noreply\.github\.com$'
